server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/training525?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 20011216
    driver-class-name: com.mysql.cj.jdbc.Driver

config:
#  驱动配置：
#  chrome_windows
#  chrome_linux
#  chrome_mac
  autoPass: chrome_mac
  # 一般环境用 src/main/resources
  # docker环境用 BOOT-INF/classes
  url: src/main/resources

mybatis:
  type-aliases-package: com.example.selenium_uni.dao.Entity
  mapper-locations: classpath:mapper/*.xml
  # 开启MyBatis的二级缓存
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true