server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/training524?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 20011216
    driver-class-name: com.mysql.cj.jdbc.Driver